### ISSUE TITLE
Error: cannot load such file -- coradoc/reverse_adoc

### ISSUE THREAD

**Issue by stuartgalt** [metanorma/suma#10]
Was trying to run  bundle exec suma build metanorma-test.yml

bundle list shows:
  * coradoc (1.1.1)
  * metanorma-cli (1.10.8)
  * suma (0.1.2)

**Comment by opoudjis** [comment]
@hmdne Removing code that external libraries depend on should have been a minor release, 1.2.0 not 1.1.1. Coradoc is now infrastructure, and it must not disrupt external code without warning. Moreover, you must notify coradoc consumers (which is me) of any major changes in the external-facing interface.

I am imposing version 1.1.* constraint on coradoc, since its external interface is now changing. That means that no updates to 1.2.* and above will be incorporated into the Metanorma stack without me testing them.

The impacted gem, deep in the stack, is metanorma-plugin-lutaml, and I will update that code now.and release it.

**Comment by opoudjis** [comment]
Gem takes two hours to run on Github Actions https://github.com/metanorma/metanorma-plugin-lutaml/issues/142 , so delay in release

**Comment by opoudjis** [comment]
Should be working now, updated to metanorma-plugin-lutaml v0.7.7, but wait another couple of hours for the release to go through (sigh).
